full_rebuild: true
name: Pymlo Accounting
author: Logan Lo
url: https://pymloaccounting.github.io/pymloaccounting
repository: https://github.com/pymloaccounting/pymloaccounting.github.io
branch: api-spec
version: 1.3
encoding: utf-8
themes:
    # General themes available: minimal, freelancer
    general: minimal
    # Code block themes available: monokai, github, vs
    code: monokai
defaults:
  -
    values:
      layout: "index"
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
